import java.util.Arrays;
import java.util.List;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static String chooseCondiment(final List<String> condiments) {
        final Scanner keyboard = new Scanner(System.in);
        boolean isValid = false;
        String condiment = null;
        while (!isValid) {
            System.out.println("Would you like to add milk or sugar to your beverage?");
            System.out.println();
            for (int i = 0; i < condiments.size(); ++i) {
                System.out.println(String.format("\t%d. %s", i + 1, condiments.get(i)));
            }
            System.out.println();
            final String prompt = String.format("Please select between 1 and %d: ", condiments.size());
            System.out.print(prompt);
            final int choice = keyboard.nextInt();
            if (choice < 1 || choice > condiments.size()) {
                System.out.print("I'm sorry, I did not understand your choice. " + prompt);
            } else {
                isValid = true;
                condiment = condiments.get(choice - 1);
            }
        }
        return condiment;
    }

    public static Beverage chooseBeverageType() {
        final Scanner keyboard = new Scanner(System.in);
        boolean isValid = false;
        Beverage beverage = null;
        while (!isValid) {
            System.out.print("Would you like to make coffee or tea? ");
            final String choice = keyboard.nextLine();
            switch (choice) {
                case "tea":
                    isValid = true;
                    beverage = new Tea();
                    break;
                case "coffee":
                    isValid = true;
                    beverage = new Coffee();
                    break;
                default:
                    System.out.println("I'm sorry, I did not understand your choice. Please type 'coffee' or 'tea'.");
            }
        }
        return beverage;
    }

    public static int chooseUnits() {
        final Scanner keyboard = new Scanner(System.in);
        int units = -1;
        while (units < 0 || units > 3) {
            System.out.print("How many units would you like to add to your beverage? [0-3] ");
            units = keyboard.nextInt();
        }
        return units;
    }

    public static void main(final String[] args) {
        System.out.println("Welcome to the Fully Automatic Beverage Vending Machine!");
        while (true) {
            final Beverage beverage = chooseBeverageType();
            if (beverage instanceof Coffee) {
                final List<String> choices = Arrays.asList("milk", "sugar", "done");
                String condiment = "";
                while (!condiment.equals("done")) {
                    condiment = chooseCondiment(choices);
                    switch (condiment) {
                        case "milk":
                            final int milkUnits = chooseUnits();
                            ((Coffee) beverage).setMilkUnits(milkUnits);
                            break;
                        case "sugar":
                            final int sugarUnits = chooseUnits();
                            ((Coffee) beverage).setSugarUnits(sugarUnits);
                    }
                }
            }
            System.out.println("You chose: " + beverage);
        }
    }
}
